### ISSUE TITLE
404 error for http://www.pilato.fr/schema/elasticsearch/elasticsearch-0.3.xsd

### ISSUE THREAD

**Issue by mastersushant** [dadoonet/spring-elasticsearch#241]
Hi ,

I am using this in our app but getting 404 issue when i am migrating my application to JDK11 env.
It is trying to validate element against schema which is not present currently and giving 404 error.

**Comment by dadoonet** [comment]
Thanks for reporting.
It appears that my DNS records have been cancelled. I had to update them again.
It can take I think up to one hour before it gets propagated.

I'm keeping it opened until I can see it fixed.

**Comment by dadoonet** [comment]
I can now open http://www.pilato.fr/schema/elasticsearch/elasticsearch-0.3.xsd

Closing. Thanks again for reporting!

**Comment by mastersushant** [comment]
Thanks its worked .

**Comment by mastersushant** [comment]
Hi ,

I am getting below exception when i am trying to deploy my code in JDK 11 and using your elasticsearch-0,3.xsd. Its looks like this version is not supported for JDK 11. Just wanted to check is there any other version which support JDK 11 and I have to do minimum code changes.
Thanks in advance.

Caused by: java.lang.ExceptionInInitializerError
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:132)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:166)
	at fr.pilato.spring.elasticsearch.ElasticsearchNodeFactoryBean.initialize(ElasticsearchNodeFactoryBean.java:122)
	at fr.pilato.spring.elasticsearch.ElasticsearchNodeFactoryBean.afterPropertiesSet(ElasticsearchNodeFactoryBean.java:72)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1571)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509)
	... 65 more
**Caused by: java.lang.UnsupportedOperationException: Boot class path mechanism is not supported**
	at java.management/sun.management.RuntimeImpl.getBootClassPath(RuntimeImpl.java:99)
	at org.elasticsearch.monitor.jvm.JvmInfo.<clinit>(JvmInfo.java:77)
	... 72 more

**Comment by dadoonet** [comment]
Could you open a ne issue? Please format the code/logs.
Also could you describe what are the versions you are using, some code may be, the reason you want to use this 0.3 xsd....
