### ISSUE TITLE
Failed to load settings from [es.properties]

### ISSUE THREAD

**Issue by leiguorui** [dadoonet/spring-elasticsearch#84]
Hi, I get the error when run my spring project.spring-elasticsearch version is 2.1.0. My spring config file is following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:util="http://www.springframework.org/schema/util"
       xmlns:elasticsearch="http://www.pilato.fr/schema/elasticsearch"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
        http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-3.0.xsd
        http://www.pilato.fr/schema/elasticsearch http://www.pilato.fr/schema/elasticsearch/elasticsearch-0.3.xsd">

    <elasticsearch:client id="esClient" esNodes="localhost:9300" />
</beans>
```
What's wrong with my cofig file, please?

**Comment by dadoonet** [comment]
Can you share the full error / stack trace?

**Comment by leiguorui** [comment]
Sorry for the late reply. It throws the following exceptions:

```java
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:157) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:211) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:288) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) ~[junit-4.9.jar:na]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:290) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) ~[junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) ~[junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) ~[junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) ~[junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) ~[junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) ~[junit-4.9.jar:na]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) ~[junit-4.9.jar:na]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) ~[junit-4.9.jar:na]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78) ~[junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212) ~[junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68) ~[junit-rt.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'esClient': Invocation of init method failed; nested exception is SettingsException[Failed to load settings from [es.properties]]; nested: NullPointerException;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:753) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:838) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148) ~[spring-test-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	... 22 common frames omitted
Caused by: org.elasticsearch.common.settings.SettingsException: Failed to load settings from [es.properties]
	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1077) ~[elasticsearch-2.1.0.jar:2.1.0]
	at fr.pilato.spring.elasticsearch.ElasticsearchTransportClientFactoryBean.buildClient(ElasticsearchTransportClientFactoryBean.java:102) ~[spring-elasticsearch-2.1.0.jar:na]
	at fr.pilato.spring.elasticsearch.ElasticsearchAbstractClientFactoryBean.initialize(ElasticsearchAbstractClientFactoryBean.java:332) ~[spring-elasticsearch-2.1.0.jar:na]
	at fr.pilato.spring.elasticsearch.ElasticsearchAbstractClientFactoryBean.afterPropertiesSet(ElasticsearchAbstractClientFactoryBean.java:327) ~[spring-elasticsearch-2.1.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 36 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78) ~[na:1.7.0_25]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113) ~[na:1.7.0_25]
	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1074) ~[elasticsearch-2.1.0.jar:2.1.0]
	... 41 common frames omitted
```

**Comment by dadoonet** [comment]
I added a junit test for it but I can't reproduce it for now. :(

Will try more testing...

**Comment by dadoonet** [comment]
Forget it. I think I found it... Super stupid bug I think.... Well, it's my code. I can say that :P
